// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import FlightMapController from "./flight_map_controller"
application.register("flight-map", FlightMapController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)
